title: 崎尾亮介 活動報告サイト
description: 公約・地域活動・一般質問の見える化
theme: minima

# プロジェクトサイト用（例: https://<user>.github.io/activity-site/）
baseurl: "/activity-site"
url: "https://sakiorYousuke-eng.github.io"

# もしユーザー/組織サイト(https://<user>.github.io/)を使うなら ↓ にする
# baseurl: "/activity-site"
# url: "https://sakiorYousuke-eng.github.io"
