title: 崎尾亮介 活動報告サイト
description: 公約・地域活動・一般質問の見える化
theme: minima

# GitHub Pages（プロジェクトサイト）
baseurl: "/activity-site"
url: "https://sakioryousuke-eng.github.io"

plugins:
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
