title: "崎尾亮介 活動サイト"
description: "日田市議会議員・崎尾亮介の活動／公約／一般質問まとめ"
url: "https://sakioryousuke-eng.github.io"
baseurl: "/activity-site"

markdown: kramdown
kramdown: { input: GFM }

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

logo: "/assets/logo.svg"         # ← ロゴを後で入れる（先にmeta側でOGP出しているので未作成でもOK）
social:
  image: "/assets/ogp.png"       # ← OGP用（jekyll-seo-tagの補助）
