title: "崎尾亮介 活動サイト"
description: "日田市議会議員・崎尾亮介の活動／公約／一般質問まとめ"
url: "https://sakioryousuke-eng.github.io"
baseurl: "/activity-site"

lang: ja
markdown: kramdown
kramdown: { input: GFM }

logo: "/assets/logo.svg"
image: "/assets/ogp.png"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
